/// <reference path="../pb_hooks/types/types.d.ts" />
migrate(
  (db) => {
    const snapshot = [
      {
        id: 'systemprofiles0',
        name: 'users',
        type: 'auth',
        system: false,
        schema: [
          {
            system: false,
            id: 'pbfieldname',
            name: 'name',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'pbfieldavatar',
            name: 'avatar',
            type: 'file',
            required: false,
            presentable: false,
            unique: false,
            options: {
              mimeTypes: [
                'image/jpg',
                'image/jpeg',
                'image/png',
                'image/svg+xml',
                'image/gif',
              ],
              thumbs: null,
              maxSelect: 1,
              maxSize: 5242880,
              protected: false,
            },
          },
          {
            system: false,
            id: '7jf2i4be',
            name: 'subscription',
            type: 'select',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['free', 'premium', 'lifetime', 'legacy'],
            },
          },
          {
            system: false,
            id: 'c1lrvx9q',
            name: 'isLegacy',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'wp3zam39',
            name: 'isFounder',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'yrezqbhc',
            name: 'discord_id',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'stcfuecz',
            name: 'unsubscribe',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'bbspvxke',
            name: 'notifyMaintenanceMode',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'umykxmck',
            name: 'welcome',
            type: 'date',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: '',
              max: '',
            },
          },
        ],
        indexes: [],
        listRule: 'id = @request.auth.id',
        viewRule: 'id = @request.auth.id',
        createRule: '',
        updateRule: 'id = @request.auth.id',
        deleteRule: null,
        options: {
          allowEmailAuth: true,
          allowOAuth2Auth: true,
          allowUsernameAuth: false,
          exceptEmailDomains: null,
          manageRule: null,
          minPasswordLength: 8,
          onlyEmailDomains: null,
          onlyVerified: false,
          requireEmail: true,
        },
      },
      {
        id: 'hsuwe2h3csch1yr',
        name: 'audit',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'cgkurilx',
            name: 'event',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'orqvyzje',
            name: 'email',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '3frdgrxe',
            name: 'user',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'systemprofiles0',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'kcj9mpcm',
            name: 'notification',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'y5lqraz7c4jvisu',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'sterc0x6',
            name: 'instance',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'etae8tuiaxl6xfv',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'rtfafgv0',
            name: 'campaign',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'yfhnigik0uvyt4m',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'vsobm1jq',
            name: 'campaign_message',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'w1vjr1edr5tsam3',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'nztvxk7i',
            name: 'sent_message',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: '18rfmj8aklx6bjq',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'chqbmew7',
            name: 'note',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '9vjfnw4e',
            name: 'raw_payload',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'w1vjr1edr5tsam3',
        name: 'campaign_messages',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'wsfnencj',
            name: 'campaign',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'yfhnigik0uvyt4m',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'lxy9jyyk',
            name: 'subject',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '4h2cqwha',
            name: 'body',
            type: 'editor',
            required: true,
            presentable: false,
            unique: false,
            options: {
              convertUrls: false,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'yfhnigik0uvyt4m',
        name: 'campaigns',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: '1laswhyx',
            name: 'name',
            type: 'text',
            required: true,
            presentable: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '4fxgwtui',
            name: 'vars',
            type: 'json',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSize: 20000,
            },
          },
          {
            system: false,
            id: 'tni65iyd',
            name: 'usersQuery',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'etae8tuiaxl6xfv',
        name: 'instances',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'p7f4wlm5',
            name: 'region',
            type: 'select',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['sfo-1', 'sfo-2', 'fra-1'],
            },
          },
          {
            system: false,
            id: 'qdtuuld1',
            name: 'subdomain',
            type: 'text',
            required: true,
            presentable: true,
            unique: false,
            options: {
              min: null,
              max: 50,
              pattern: '^[a-z][a-z0-9-]{2,39}$',
            },
          },
          {
            system: false,
            id: 'rbj14krn',
            name: 'uid',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'systemprofiles0',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'c2y74d7h',
            name: 'status',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '4ydffkv3',
            name: 'version',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '3yu1db4p',
            name: 'secrets',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 2000000,
            },
          },
          {
            system: false,
            id: 'mexrkb5z',
            name: 'maintenance',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'hkt4q8yk',
            name: 'syncAdmin',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: '5oz9huwg',
            name: 'cname',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern:
                '^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,24}$',
            },
          },
          {
            system: false,
            id: 'a5qqq8fs',
            name: 'dev',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'hsoandop',
            name: 'cname_active',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'k7nxxzdr',
            name: 's3',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: '7n6rny9w7n52mvi',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'rofy4mta',
            name: 'notifyMaintenanceMode',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: '7bi0jspk',
            name: 'suspension',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
        ],
        indexes: [
          'CREATE UNIQUE INDEX `idx_unique_qdtuuld1` ON `instances` (`subdomain`)',
          'CREATE INDEX `idx_DKUSkMx` ON `instances` (`status`)',
          'CREATE INDEX `idx_fhfKrpl` ON `instances` (`uid`)',
          'CREATE INDEX `idx_TfdgNnO` ON `instances` (`maintenance`)',
          'CREATE INDEX `idx_FrmHehp` ON `instances` (`created`)',
          'CREATE INDEX `idx_tNMeylJ` ON `instances` (`updated`)',
          "CREATE UNIQUE INDEX `idx_rBYwAXi` ON `instances` (`cname`) WHERE cname != ''",
        ],
        listRule: 'uid=@request.auth.id',
        viewRule: 'uid = @request.auth.id',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: '6m8h2sy0nutig46',
        name: 'message_templates',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'si53ohkr',
            name: 'slug',
            type: 'text',
            required: true,
            presentable: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'zarqosgs',
            name: 'subject',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'woodsq1c',
            name: 'body_html',
            type: 'editor',
            required: false,
            presentable: false,
            unique: false,
            options: {
              convertUrls: false,
            },
          },
        ],
        indexes: [
          'CREATE UNIQUE INDEX `idx_7e53x5A` ON `message_templates` (`slug`)',
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'y5lqraz7c4jvisu',
        name: 'notifications',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'dwn9j8oo',
            name: 'channel',
            type: 'select',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['email', 'lemonbot'],
            },
          },
          {
            system: false,
            id: 'ry5pnrld',
            name: 'user',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'systemprofiles0',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'fksunfv1',
            name: 'instance',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'etae8tuiaxl6xfv',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'gmqwgamf',
            name: 'campaign',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'yfhnigik0uvyt4m',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'crksfxsv',
            name: 'campaign_message',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'w1vjr1edr5tsam3',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'qoshryii',
            name: 'sent_message',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: '18rfmj8aklx6bjq',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'cmkxbt9j',
            name: 'payment',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'iff2jfzb89dwiov',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'ezyqswtg',
            name: 'payload',
            type: 'json',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSize: 2000000,
            },
          },
          {
            system: false,
            id: 'sgeq9rbv',
            name: 'delivered',
            type: 'date',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: '',
              max: '',
            },
          },
          {
            system: false,
            id: 'v8zn89fa',
            name: 'message_template',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: '6m8h2sy0nutig46',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'zoqchc2l',
            name: 'message_template_vars',
            type: 'json',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSize: 2000000,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'iff2jfzb89dwiov',
        name: 'payments',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'uhurtdtl',
            name: 'user',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'systemprofiles0',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'tgaer8rx',
            name: 'payment_id',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
        ],
        indexes: [
          'CREATE INDEX `idx_DezkBvw` ON `payments` (`user`)',
          'CREATE INDEX `idx_A5j325f` ON `payments` (`payment_id`)',
          'CREATE INDEX `idx_qBPC3VW` ON `payments` (`created`)',
          'CREATE UNIQUE INDEX `idx_NPkwSnu` ON `payments` (`payment_id`)',
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: '7n6rny9w7n52mvi',
        name: 's3',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'yvy0exvk',
            name: 'instance',
            type: 'relation',
            required: false,
            presentable: true,
            unique: false,
            options: {
              collectionId: 'etae8tuiaxl6xfv',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'kz6u1z1p',
            name: 'endpoint',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'etcgfvgc',
            name: 'access_key',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'fn8ulajr',
            name: 'secret',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'kktzqpxi',
            name: 'bucket',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'fysmrb1v',
            name: 'region',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: '18rfmj8aklx6bjq',
        name: 'sent_messages',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'wuitrzp6',
            name: 'user',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'systemprofiles0',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'yzvlcy7m',
            name: 'message',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'kigwtdjb',
            name: 'campaign_message',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'w1vjr1edr5tsam3',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'aif4h1j462iqopo',
        name: 'settings',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'a0gyirdi',
            name: 'name',
            type: 'text',
            required: true,
            presentable: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'xso1u0og',
            name: 'value',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 2000000,
            },
          },
        ],
        indexes: ['CREATE INDEX `idx_qMbeGsg` ON `settings` (`name`)'],
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: 'h055gvw3oqi2fs0',
        name: 'duplicate_emails',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'hy2ph2kc',
            name: 'email_prefix',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
          {
            system: false,
            id: 'fq92utcd',
            name: 'email_domain',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
          {
            system: false,
            id: 'ayhytcq7',
            name: 'count',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            "SELECT \n  (ROW_NUMBER() OVER()) as id,\n    SUBSTR(email, 1, INSTR(email, '@') - 1) AS email_prefix,\n    SUBSTR(email, INSTR(email, '@')) AS email_domain,\n    COUNT(*) AS count\nFROM \n    (SELECT \n         CASE \n             WHEN INSTR(SUBSTR(email, 1, INSTR(email, '@') - 1), '+') > 0 \n             THEN SUBSTR(email, 1, INSTR(SUBSTR(email, 1, INSTR(email, '@') - 1), '+') - 1) || SUBSTR(email, INSTR(email, '@')) \n             ELSE email \n         END AS email \n     FROM users)\nGROUP BY \n    email_prefix, email_domain;\n",
        },
      },
      {
        id: 'thjxyrzo35idz7s',
        name: 'growth_by_day',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'xezxdxj3',
            name: 'created_day',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
          {
            system: false,
            id: 'waxqxcex',
            name: 'users_count',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
          {
            system: false,
            id: 'kcllgjtf',
            name: 'instances_count',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            "SELECT \n    (ROW_NUMBER() OVER()) as id,\n    created_day,\n    SUM(users_count) AS users_count,\n    SUM(instances_count) AS instances_count\nFROM (\n    SELECT \n        strftime('%Y-%m-%d', users.created) AS created_day, \n        COUNT(*) AS users_count, \n        0 AS instances_count\n    FROM \n        users \n    GROUP BY \n        created_day\n    UNION ALL\n    SELECT \n        strftime('%Y-%m-%d', instances.created) AS created_day, \n        0 AS users_count, \n        COUNT(*) AS instances_count\n    FROM \n        instances \n    GROUP BY \n        created_day\n) \nGROUP BY \n    created_day\norder by created_day desc\n",
        },
      },
      {
        id: '4jyrkxcora6bl8r',
        name: 'legacy_users',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'w7p5hczv',
            name: 'email',
            type: 'email',
            required: false,
            presentable: false,
            unique: false,
            options: {
              exceptDomains: null,
              onlyDomains: null,
            },
          },
          {
            system: false,
            id: 'krprbqrz',
            name: 'isFounder',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'bl2nc8ac',
            name: 'subscription',
            type: 'select',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['free', 'premium', 'lifetime', 'legacy'],
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            'select u.id, u.email,u.isFounder,u.subscription,u.created,u.updated from verified_users u where u.isLegacy=1',
        },
      },
      {
        id: 'buq519uv711078p',
        name: 'stats',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'hy7njiza',
            name: 'founder_slots_remaining',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
          {
            system: false,
            id: 'qpbvc5ut',
            name: 'total_users',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'qlnytqmj',
            name: 'total_legacy_subscribers',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'zbaplkwv',
            name: 'total_free_subscribers',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'exu5uwpy',
            name: 'total_pro_subscribers',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'btak3el2',
            name: 'total_lifetime_subscribers',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'enur9h6p',
            name: 'new_users_last_hour',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'zypx3s5g',
            name: 'new_users_last_24_hours',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: '8o6qwwpk',
            name: 'new_users_last_7_days',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'owppxkp1',
            name: 'new_users_last_30_days',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 't5hfbuy0',
            name: 'total_instances',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'hy6ksvwr',
            name: 'total_instances_last_hour',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'esvqpfks',
            name: 'total_instances_last_24_hours',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'yl9gsbnh',
            name: 'total_instances_last_7_days',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'fob5xhbs',
            name: 'total_instances_last_30_days',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'upjeewnx',
            name: 'new_instances_last_hour',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: '2quxsopb',
            name: 'new_instances_last_24_hours',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: '9u8mi3xv',
            name: 'new_instances_last_7_days',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
          {
            system: false,
            id: 'crqnqirt',
            name: 'new_instances_last_30_days',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            "SELECT\n  (ROW_NUMBER() OVER()) as id,\n    (select value from settings where name='founders-edition-count') as founder_slots_remaining, \n    COUNT(DISTINCT users.id) AS total_users,\n    COUNT(DISTINCT CASE WHEN users.subscription ='legacy' THEN users.id END) AS total_legacy_subscribers,\n    COUNT(DISTINCT CASE WHEN users.subscription ='free' THEN users.id END) AS total_free_subscribers,\n    COUNT(DISTINCT CASE WHEN users.subscription= 'premium' THEN users.id END) AS total_pro_subscribers,\n    COUNT(DISTINCT CASE WHEN users.subscription= 'lifetime' THEN users.id END) AS total_lifetime_subscribers,\n  \n    COUNT(DISTINCT CASE WHEN users.created > DATETIME('now', '-1 hour') THEN users.id END) AS new_users_last_hour,\n    COUNT(DISTINCT CASE WHEN users.created > DATETIME('now', '-24 hours') THEN users.id END) AS new_users_last_24_hours,\n    COUNT(DISTINCT CASE WHEN users.created > DATETIME('now', '-7 days') THEN users.id END) AS new_users_last_7_days,\n    COUNT(DISTINCT CASE WHEN users.created > DATETIME('now', '-30 days') THEN users.id END) AS new_users_last_30_days,\n  \n    COUNT(DISTINCT instances.id ) AS total_instances,\n    COUNT(DISTINCT CASE WHEN instances.updated > DATETIME('now', '-1 hour') THEN instances.id END) AS total_instances_last_hour,\n    COUNT(DISTINCT CASE WHEN instances.updated > DATETIME('now', '-24 hours') THEN instances.id END) AS total_instances_last_24_hours,\n    COUNT(DISTINCT CASE WHEN instances.updated > DATETIME('now', '-7 days') THEN instances.id END) AS total_instances_last_7_days,\n    COUNT(DISTINCT CASE WHEN instances.updated > DATETIME('now', '-30 days') THEN instances.id END) AS total_instances_last_30_days,\n  \n    COUNT(DISTINCT CASE WHEN instances.created > DATETIME('now', '-1 hour') THEN instances.id END) AS new_instances_last_hour,\n    COUNT(DISTINCT CASE WHEN instances.created > DATETIME('now', '-24 hours') THEN instances.id END) AS new_instances_last_24_hours,\n    COUNT(DISTINCT CASE WHEN instances.created > DATETIME('now', '-7 days') THEN instances.id END) AS new_instances_last_7_days,\n    COUNT(DISTINCT CASE WHEN instances.created > DATETIME('now', '-30 days') THEN instances.id END) AS new_instances_last_30_days\n  \nFROM\n    verified_users users\nLEFT JOIN\n    instances ON users.id = instances.uid;\n",
        },
      },
      {
        id: 's00x84jumfjcuvc',
        name: 'subscribed_users',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'bm01zt0c',
            name: 'username',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'q5mz7sy4',
            name: 'email',
            type: 'email',
            required: false,
            presentable: false,
            unique: false,
            options: {
              exceptDomains: null,
              onlyDomains: null,
            },
          },
          {
            system: false,
            id: 'rsimzkmj',
            name: 'subscription',
            type: 'select',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['free', 'premium', 'lifetime', 'legacy'],
            },
          },
          {
            system: false,
            id: 'cqqlheei',
            name: 'isLegacy',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 't8n4if5z',
            name: 'isFounder',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            'select id, username, email, subscription, isLegacy, isFounder,created,updated from users where verified=1 and unsubscribe=0',
        },
      },
      {
        id: '1xetiik3maqvihl',
        name: 'unpaid_instances',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'kyyleyhn',
            name: 'uid',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'systemprofiles0',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: 1,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'ycqtfiup',
            name: 'subdomain',
            type: 'text',
            required: true,
            presentable: true,
            unique: false,
            options: {
              min: null,
              max: 50,
              pattern: '^[a-z][a-z0-9-]{2,39}$',
            },
          },
          {
            system: false,
            id: 'exvjxk2z',
            name: 'suspension',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            'select instances.id, uid, subdomain, suspension, instances.updated from instances join verified_users vu where vu.id = uid and (vu.subscription="free" or vu.subscription = "legacy")',
        },
      },
      {
        id: 'ledwhu6imoityio',
        name: 'unverified_users',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'qb7sqdt4',
            name: 'username',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'jen5x1yw',
            name: 'email',
            type: 'email',
            required: false,
            presentable: false,
            unique: false,
            options: {
              exceptDomains: null,
              onlyDomains: null,
            },
          },
          {
            system: false,
            id: 'ky0mtxk7',
            name: 'subscription',
            type: 'select',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['free', 'premium', 'lifetime', 'legacy'],
            },
          },
          {
            system: false,
            id: 'iawkzwas',
            name: 'isLegacy',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'vhijmtq6',
            name: 'isFounder',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            'select id, username, email, subscription, isLegacy, isFounder,created,updated from users where verified = 0',
        },
      },
      {
        id: '7vzz1jr2us7mwmx',
        name: 'user_growth_by_month',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'kbncraou',
            name: 't',
            type: 'json',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSize: 1,
            },
          },
          {
            system: false,
            id: 'laq2glwk',
            name: 'c',
            type: 'number',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: false,
            },
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            "SELECT \n   (ROW_NUMBER() OVER()) as id,\n    strftime('%Y-%m', created) AS t, \n    COUNT(*) AS c \nFROM \n    verified_users as users\nGROUP BY \n    t\n\torder by t desc\n",
        },
      },
      {
        id: '4kshuv7r3jdrst4',
        name: 'verified_users',
        type: 'view',
        system: false,
        schema: [
          {
            system: false,
            id: 'p84zuh5s',
            name: 'username',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: '9cvv0zph',
            name: 'email',
            type: 'email',
            required: false,
            presentable: false,
            unique: false,
            options: {
              exceptDomains: null,
              onlyDomains: null,
            },
          },
          {
            system: false,
            id: 's1xad73d',
            name: 'subscription',
            type: 'select',
            required: true,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: ['free', 'premium', 'lifetime', 'legacy'],
            },
          },
          {
            system: false,
            id: 'jbcgvipx',
            name: 'isLegacy',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: 'fhu3o5ub',
            name: 'isFounder',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {
          query:
            'select id, username, email, subscription, isLegacy, isFounder,created,updated from users where verified = 1',
        },
      },
    ]

    const collections = snapshot.map((item) => new Collection(item))

    return Dao(db).importCollections(collections, true, null)
  },
  (db) => {
    return null
  },
)
