/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      id: 'p7edgeslive01ab',
      name: 'edges',
      type: 'base',
      system: false,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'ed9geid01',
          max: 64,
          min: 1,
          name: 'edge_id',
          pattern: '^[a-zA-Z0-9][a-zA-Z0-9._-]*$',
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'ed9label1',
          max: 128,
          min: 0,
          name: 'label',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'ed9last01',
          max: '',
          min: '',
          name: 'last_seen',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: 'ed9stat01',
          maxSelect: 1,
          name: 'status',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['online', 'stale', 'offline'],
        },
        {
          hidden: false,
          id: 'ed9json01',
          maxSize: 2000000,
          name: 'stats',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      indexes: ['CREATE UNIQUE INDEX `idx_edges_edge_id` ON `edges` (`edge_id`)'],
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
    })

    app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('edges')
    app.delete(collection)
  }
)
