/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const snapshot = [
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 1209600,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/login/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: '',
        deleteRule: null,
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 10,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9_]{50}',
            help: '',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: true,
            required: true,
            system: true,
            type: 'email',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            autogeneratePattern: 'users[0-9]{6}',
            help: '',
            hidden: false,
            id: 'text4166911607',
            max: 150,
            min: 3,
            name: 'username',
            pattern: '^[\\w][\\w\\.\\-]*$',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'pbfieldname',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'pbfieldavatar',
            maxSelect: 1,
            maxSize: 5242880,
            mimeTypes: ['image/jpg', 'image/jpeg', 'image/png', 'image/svg+xml', 'image/gif'],
            name: 'avatar',
            presentable: false,
            protected: false,
            required: false,
            system: false,
            thumbs: null,
            type: 'file',
          },
          {
            help: '',
            hidden: false,
            id: '7jf2i4be',
            maxSelect: 1,
            name: 'subscription',
            presentable: false,
            required: true,
            system: false,
            type: 'select',
            values: ['free', 'unpaid', 'premium', 'founder', 'flounder', 'legacy'],
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'yrezqbhc',
            max: 0,
            min: 0,
            name: 'discord_id',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'stcfuecz',
            name: 'unsubscribe',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bbspvxke',
            name: 'notifyMaintenanceMode',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'umykxmck',
            max: '',
            min: '',
            name: 'welcome',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            help: '',
            hidden: false,
            id: '8i4kdjgr',
            maxSelect: 1,
            name: 'subscription_interval',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['month', 'year', 'life'],
          },
          {
            help: '',
            hidden: false,
            id: 'mny9d9cl',
            maxSize: 2000000,
            name: 's3',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'we768a9l',
            max: 0,
            min: 0,
            name: 'suspension',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'konhuwum',
            name: 'double_verified',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'u4ckg6um',
            max: null,
            min: null,
            name: 'subscription_quantity',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            convertURLs: false,
            help: '',
            hidden: false,
            id: '5jejgdlc',
            maxSize: 0,
            name: 'notes',
            presentable: false,
            required: false,
            system: false,
            type: 'editor',
          },
          {
            help: '',
            hidden: false,
            id: 'usratelm',
            maxSize: 2000000,
            name: 'rate_limits',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 120,
        },
        id: 'systemprofiles0',
        indexes: [
          'CREATE UNIQUE INDEX `_systemprofiles0_username_idx` ON `users` (username COLLATE NOCASE)',
          "CREATE UNIQUE INDEX `_systemprofiles0_email_idx` ON `users` (`email`) WHERE `email` != ''",
          'CREATE UNIQUE INDEX `_systemprofiles0_tokenKey_idx` ON `users` (`tokenKey`)',
          'CREATE INDEX `idx_dVbmhXb` ON `users` (`subscription`)',
          'CREATE INDEX `idx_3BXGFzv` ON `users` (`double_verified`)',
          'CREATE INDEX `idx_vBLE6dl` ON `users` (`suspension`)',
        ],
        listRule: 'id = @request.auth.id',
        manageRule: null,
        mfa: {
          duration: 600,
          enabled: false,
          rule: '',
        },
        name: 'users',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: '',
            id: '',
            name: '',
            username: 'username',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/login/password-reset/confirm/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: false,
        type: 'auth',
        updateRule: null,
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/login/confirm-account/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 604800,
        },
        viewRule: 'id = @request.auth.id',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'cgkurilx',
            max: 0,
            min: 0,
            name: 'event',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'systemprofiles0',
            help: '',
            hidden: false,
            id: '3frdgrxe',
            maxSelect: 1,
            minSelect: 0,
            name: 'user',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'chqbmew7',
            max: 0,
            min: 0,
            name: 'note',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '9vjfnw4e',
            max: 0,
            min: 0,
            name: 'raw_payload',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 's1npfwfb',
            maxSize: 2000000,
            name: 'context',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'hsuwe2h3csch1yr',
        indexes: [],
        listRule: null,
        name: 'audit',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: false,
            collectionId: 'yfhnigik0uvyt4m',
            help: '',
            hidden: false,
            id: 'wsfnencj',
            maxSelect: 1,
            minSelect: 0,
            name: 'campaign',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'lxy9jyyk',
            max: 0,
            min: 0,
            name: 'subject',
            pattern: '',
            presentable: true,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            convertURLs: false,
            help: '',
            hidden: false,
            id: '4h2cqwha',
            maxSize: 0,
            name: 'body',
            presentable: false,
            required: true,
            system: false,
            type: 'editor',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'w1vjr1edr5tsam3',
        indexes: [],
        listRule: null,
        name: 'campaign_messages',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '1laswhyx',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: true,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: '4fxgwtui',
            maxSize: 20000,
            name: 'vars',
            presentable: false,
            required: true,
            system: false,
            type: 'json',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'tni65iyd',
            max: 0,
            min: 0,
            name: 'usersQuery',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'yfhnigik0uvyt4m',
        indexes: [],
        listRule: null,
        name: 'campaigns',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'qdtuuld1',
            max: 50,
            min: 0,
            name: 'subdomain',
            pattern: '^[a-z][a-z0-9-]{2,39}$',
            presentable: true,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'systemprofiles0',
            help: '',
            hidden: false,
            id: 'rbj14krn',
            maxSelect: 1,
            minSelect: 0,
            name: 'uid',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'c2y74d7h',
            max: 0,
            min: 0,
            name: 'status',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '4ydffkv3',
            max: 0,
            min: 0,
            name: 'version',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: '3yu1db4p',
            maxSize: 2000000,
            name: 'secrets',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            help: '',
            hidden: false,
            id: 'mexrkb5z',
            name: 'power',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'hkt4q8yk',
            name: 'syncAdmin',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'a5qqq8fs',
            name: 'dev',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '7bi0jspk',
            max: 0,
            min: 0,
            name: 'suspension',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'gbfsfi0g',
            max: null,
            min: null,
            name: 'idleTtl',
            onlyInt: false,
            presentable: false,
            required: false,
            system: false,
            type: 'number',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '5oz9huwg',
            max: 0,
            min: 0,
            name: 'cname',
            pattern: '^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,24}$',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'hsoandop',
            name: 'cname_active',
            presentable: false,
            required: false,
            system: false,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: '5q2bapw9',
            maxSize: 2000000,
            name: 'webhooks',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: '9kcgvnac',
            max: 0,
            min: 0,
            name: 'notes',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'fwtrstip',
            maxSize: 2000000,
            name: 'trusted_ips',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            help: '',
            hidden: false,
            id: 'fwproxyip',
            maxSize: 2000000,
            name: 'proxy_ips',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            help: '',
            hidden: false,
            id: 'fwratelmt',
            maxSize: 2000000,
            name: 'rate_limits',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'etae8tuiaxl6xfv',
        indexes: [
          'CREATE UNIQUE INDEX `idx_unique_qdtuuld1` ON `instances` (`subdomain`)',
          'CREATE INDEX `idx_DKUSkMx` ON `instances` (`status`)',
          'CREATE INDEX `idx_fhfKrpl` ON `instances` (`uid`)',
          'CREATE INDEX `idx_TfdgNnO` ON `instances` (`power`)',
          'CREATE INDEX `idx_FrmHehp` ON `instances` (`created`)',
          'CREATE INDEX `idx_tNMeylJ` ON `instances` (`updated`)',
          "CREATE UNIQUE INDEX `idx_rBYwAXi` ON `instances` (`cname`) WHERE cname != ''",
        ],
        listRule: 'uid=@request.auth.id',
        name: 'instances',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: 'uid = @request.auth.id',
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'si53ohkr',
            max: 0,
            min: 0,
            name: 'slug',
            pattern: '',
            presentable: true,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'zarqosgs',
            max: 0,
            min: 0,
            name: 'subject',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            convertURLs: false,
            help: '',
            hidden: false,
            id: 'woodsq1c',
            maxSize: 0,
            name: 'body_html',
            presentable: false,
            required: false,
            system: false,
            type: 'editor',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: '6m8h2sy0nutig46',
        indexes: ['CREATE UNIQUE INDEX `idx_7e53x5A` ON `message_templates` (`slug`)'],
        listRule: null,
        name: 'message_templates',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'dwn9j8oo',
            maxSelect: 1,
            name: 'channel',
            presentable: false,
            required: false,
            system: false,
            type: 'select',
            values: ['email', 'lemonbot'],
          },
          {
            cascadeDelete: true,
            collectionId: 'systemprofiles0',
            help: '',
            hidden: false,
            id: 'ry5pnrld',
            maxSelect: 1,
            minSelect: 0,
            name: 'user',
            presentable: false,
            required: false,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'ezyqswtg',
            maxSize: 2000000,
            name: 'payload',
            presentable: false,
            required: true,
            system: false,
            type: 'json',
          },
          {
            help: '',
            hidden: false,
            id: 'sgeq9rbv',
            max: '',
            min: '',
            name: 'delivered',
            presentable: false,
            required: false,
            system: false,
            type: 'date',
          },
          {
            cascadeDelete: false,
            collectionId: '6m8h2sy0nutig46',
            help: '',
            hidden: false,
            id: 'v8zn89fa',
            maxSelect: 1,
            minSelect: 0,
            name: 'message_template',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            help: '',
            hidden: false,
            id: 'zoqchc2l',
            maxSize: 2000000,
            name: 'message_template_vars',
            presentable: false,
            required: true,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'y5lqraz7c4jvisu',
        indexes: [],
        listRule: null,
        name: 'notifications',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'systemprofiles0',
            help: '',
            hidden: false,
            id: 'uhurtdtl',
            maxSelect: 1,
            minSelect: 0,
            name: 'user',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'tgaer8rx',
            max: 0,
            min: 0,
            name: 'payment_id',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: false,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'iff2jfzb89dwiov',
        indexes: [
          'CREATE INDEX `idx_DezkBvw` ON `payments` (`user`)',
          'CREATE INDEX `idx_A5j325f` ON `payments` (`payment_id`)',
          'CREATE INDEX `idx_qBPC3VW` ON `payments` (`created`)',
          'CREATE UNIQUE INDEX `idx_NPkwSnu` ON `payments` (`payment_id`)',
        ],
        listRule: null,
        name: 'payments',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cascadeDelete: true,
            collectionId: 'systemprofiles0',
            help: '',
            hidden: false,
            id: 'wuitrzp6',
            maxSelect: 1,
            minSelect: 0,
            name: 'user',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            cascadeDelete: false,
            collectionId: 'w1vjr1edr5tsam3',
            help: '',
            hidden: false,
            id: 'kigwtdjb',
            maxSelect: 1,
            minSelect: 0,
            name: 'campaign_message',
            presentable: false,
            required: true,
            system: false,
            type: 'relation',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: '18rfmj8aklx6bjq',
        indexes: ['CREATE UNIQUE INDEX `idx_tsm2mRA` ON `sent_messages` (\n  `user`,\n  `campaign_message`\n)'],
        listRule: null,
        name: 'sent_messages',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'mxwxp5sy',
            max: 0,
            min: 0,
            name: 'name',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: false,
            type: 'text',
          },
          {
            help: '',
            hidden: false,
            id: 'vnvomsqv',
            maxSize: 2000000,
            name: 'value',
            presentable: false,
            required: false,
            system: false,
            type: 'json',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: false,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: false,
            type: 'autodate',
          },
        ],
        id: 'mtzs71nx5kq1vmz',
        indexes: ['CREATE INDEX `idx_wiKCiVq` ON `settings` (`name`)'],
        listRule: null,
        name: 'settings',
        system: false,
        type: 'base',
        updateRule: null,
        viewRule: null,
      },
      {
        authAlert: {
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'Login from a new location',
          },
          enabled: true,
        },
        authRule: '',
        authToken: {
          duration: 1209600,
        },
        confirmEmailChangeTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}" target="_blank" rel="noopener">Confirm new email</a>\n</p>\n<p><i>If you didn\'t ask to change your email address, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Confirm your {APP_NAME} new email address',
        },
        createRule: null,
        deleteRule: null,
        emailChangeToken: {
          duration: 1800,
        },
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 0,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 8,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '[a-zA-Z0-9]{50}',
            help: '',
            hidden: true,
            id: 'text2504183744',
            max: 60,
            min: 30,
            name: 'tokenKey',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            exceptDomains: null,
            help: '',
            hidden: false,
            id: 'email3885137012',
            name: 'email',
            onlyDomains: null,
            presentable: false,
            required: true,
            system: true,
            type: 'email',
          },
          {
            help: '',
            hidden: false,
            id: 'bool1547992806',
            name: 'emailVisibility',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            help: '',
            hidden: false,
            id: 'bool256245529',
            name: 'verified',
            presentable: false,
            required: false,
            system: true,
            type: 'bool',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        fileToken: {
          duration: 120,
        },
        id: 'pbc_3142635823',
        indexes: [
          'CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`)',
          "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE `email` != ''",
        ],
        listRule: null,
        manageRule: null,
        mfa: {
          duration: 600,
          enabled: false,
          rule: '',
        },
        name: '_superusers',
        oauth2: {
          enabled: false,
          mappedFields: {
            avatarURL: '',
            id: '',
            name: '',
            username: '',
          },
        },
        otp: {
          duration: 180,
          emailTemplate: {
            body: "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
            subject: 'OTP for {APP_NAME}',
          },
          enabled: false,
          length: 8,
        },
        passwordAuth: {
          enabled: true,
          identityFields: ['email'],
        },
        passwordResetToken: {
          duration: 1800,
        },
        resetPasswordTemplate: {
          body: '<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}" target="_blank" rel="noopener">Reset password</a>\n</p>\n<p><i>If you didn\'t ask to reset your password, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Reset your {APP_NAME} password',
        },
        system: true,
        type: 'auth',
        updateRule: null,
        verificationTemplate: {
          body: '<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class="btn" href="{APP_URL}/_/#/auth/confirm-verification/{TOKEN}" target="_blank" rel="noopener">Verify</a>\n</p>\n<p><i>If you didn\'t recently register, please ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>',
          subject: 'Verify your {APP_NAME} email',
        },
        verificationToken: {
          duration: 86400,
        },
        viewRule: null,
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text2462348188',
            max: 0,
            min: 0,
            name: 'provider',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1044722854',
            max: 0,
            min: 0,
            name: 'providerId',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2281828961',
        indexes: [
          'CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (collectionRef, recordRef, provider)',
          'CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (collectionRef, provider, providerId)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_externalAuths',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text1582905952',
            max: 0,
            min: 0,
            name: 'method',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_2279338944',
        indexes: ['CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (collectionRef,recordRef)'],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_mfas',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule: null,
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            cost: 8,
            help: '',
            hidden: true,
            id: 'password901924565',
            max: 0,
            min: 0,
            name: 'password',
            pattern: '',
            presentable: false,
            required: true,
            system: true,
            type: 'password',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: true,
            id: 'text3866985172',
            max: 0,
            min: 0,
            name: 'sentTo',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: false,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_1638494021',
        indexes: ['CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (collectionRef, recordRef)'],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_otps',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
      {
        createRule: null,
        deleteRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        fields: [
          {
            autogeneratePattern: '[a-z0-9]{15}',
            help: '',
            hidden: false,
            id: 'text3208210256',
            max: 15,
            min: 15,
            name: 'id',
            pattern: '^[a-z0-9]+$',
            presentable: false,
            primaryKey: true,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text455797646',
            max: 0,
            min: 0,
            name: 'collectionRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text127846527',
            max: 0,
            min: 0,
            name: 'recordRef',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            autogeneratePattern: '',
            help: '',
            hidden: false,
            id: 'text4228609354',
            max: 0,
            min: 0,
            name: 'fingerprint',
            pattern: '',
            presentable: false,
            primaryKey: false,
            required: true,
            system: true,
            type: 'text',
          },
          {
            hidden: false,
            id: 'autodate2990389176',
            name: 'created',
            onCreate: true,
            onUpdate: false,
            presentable: false,
            system: true,
            type: 'autodate',
          },
          {
            hidden: false,
            id: 'autodate3332085495',
            name: 'updated',
            onCreate: true,
            onUpdate: true,
            presentable: false,
            system: true,
            type: 'autodate',
          },
        ],
        id: 'pbc_4275539003',
        indexes: [
          'CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (collectionRef, recordRef, fingerprint)',
        ],
        listRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
        name: '_authOrigins',
        system: true,
        type: 'base',
        updateRule: null,
        viewRule:
          "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      },
    ]

    return app.importCollections(snapshot, false)
  },
  (app) => {
    return null
  }
)
