FROM nginx:latest

ARG POCKETBASE_VERSION=0.7.2

RUN apt update
RUN apt install -y unzip systemd systemd-sysv
RUN apt install -y systemd
RUN apt install -y systemd-sysv

# Download Pocketbase and install it for AMD64
ADD https://github.com/pocketbase/pocketbase/releases/download/v${POCKETBASE_VERSION}/pocketbase_${POCKETBASE_VERSION}_linux_amd64.zip /tmp/pocketbase.zip
RUN unzip /tmp/pocketbase.zip -d /usr/local/bin/
RUN chmod +x /usr/local/bin/pocketbase

ADD ./data /data
ADD ./nginx/conf.d /etc/nginx/conf.d

COPY ./pockethost-db.service /etc/systemd/system/pockethost-db.service
RUN systemctl enable pockethost-db.service
# RUN echo "::respawn:/usr/local/bin/pocketbase serve --http '127.0.0.1:8090' --dir /data/pockethost" >> /etc/inittab

# Notify Docker that the container wants to expose a port.
EXPOSE 80
